In [1]:
# np.reshape (*,*,'C') C tells the way the values have to be added in the matrix
# 'C' here means that the style of C language has to be followed, meaning filling values ROW wise: the DEFAULT way

# The other option is np.reshape(*,*,'F') F: to follow style of Fortran language
# F: filling it column wise, which is also how it's done by default in R

In [2]:
# np.array()  combines data elements to a matrix

In [3]:
import numpy as np

In [5]:
mydata= np.arange(0,20) #arange as in ' a range'  AND NOT arrange
# starts with 0, goes till 20 not inclusive
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
np.reshape(mydata,(5,4))
# np.reshape(source, (rows,columns))
# np.reshape(Re-shape what?, (no of rows, no of columns))
# NOTE: The default is opposite to R. Here rows get populated first. 0-3 are in first ROW

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
matr1=np.reshape(mydata,(5,4), order='C')
matr1  #like C is the default in Python

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
# Printing 10 value to check understanding of indexation
matr1[3,3]

15

In [9]:
# WRONG!!! Indexation starts at 0, Doofus
matr1[2,2]

10

In [10]:
# Yo! Got it right now. 

In [11]:
matr2= np.reshape[mydata, (5,4), Order= 'F']  
# 1. You use () and NOT [] after np.reshape
# 2. o in order has to be in small letters, not capital O 

SyntaxError: invalid syntax (<ipython-input-11-338b262f9d4b>, line 1)

In [17]:
matr2= np.reshape (mydata,(5,4), order= 'F')
matr2 # This is the default way in R

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [18]:
# Accessing element 10 now
matr2[0,2]

10

In [19]:
# OOP Concept
# np.reshape(mydata,(5,4))
type(mydata)

numpy.ndarray

In [20]:
# mydata is an array , it is an object
# Instead of calling np package and then saying np.reshape
# we can directly call it from the object, like:
mydata.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
r1= ["I", "am", "happy"]
r2= ["What","a","day"]
r3=[1,2,3]
# Created lists

In [24]:
# List inside a list
[r1,r2,r3]

[['I', 'am', 'happy'], ['What', 'a', 'day'], [1, 2, 3]]

In [25]:
np.array([r1,r2,r3]) # here, converts lists to a matrix

array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3']], dtype='<U5')

In [26]:
# <U5 means less than 5 unicode characters
# to not see that:
print(np.array([r1,r2,r3]))

[['I' 'am' 'happy']
 ['What' 'a' 'day']
 ['1' '2' '3']]


In [ ]:
# numbers changed to strings, since matrices can have only one data type