In [1]:
# There are numpy arrays, and there are python arrays
# Numpy arrays already enabled in Anaconda?/ or are better (re-check)
# Hence we are using Numpy Arrays

In [2]:
import numpy as np

In [3]:
l=[21,234,545,123] #list
a=np.array(l)

In [4]:
a

array([ 21, 234, 545, 123])

In [5]:
#Why use array instead of list?
# An array is  like a vector in R, can't have different data types in an array

In [6]:
b=np.array([12,3.5,True,'abc'])

In [7]:
print(b)

['12' '3.5' 'True' 'abc']


In [8]:
# All of the datatypes have been converted into String ('' shows that)

In [9]:
# Since this is OOPs, every list stores with itself methods, for e.g.
# id we type "l." and press tab key, we will be prompted a bunch of methods(actions) to be performed on the list

In [11]:
l.pop() #pops the last value out of the list

123

In [12]:
print(l)  # the last value 123 no more in the list, it has been popped out

[21, 234, 545]


In [13]:
# Trying the same thing with arrays gives us LOT MANY MORE options as compared to the ones available for list

In [14]:
a.mean() #directly allows us to calculate mean of the array

230.75

---

In [15]:
# ~~~~~~~~~~~~~`` Slicing Lists ~~~~~~~~~~~~~~

In [16]:
a[1:]

array([234, 545, 123])

In [17]:
a[1:3]

array([234, 545])

In [18]:
# with list, when you slice a list, you're creating other list, a= b[1:3], will pass on values in those indices
# In Array, you are working with a part of the array on slicing, not a copy, so changes made affect the original array
# You're still working with the original arrat

In [22]:
a

array([ 21, 234, 545, 123])

In [20]:
b

array(['12', '3.5', 'True', 'abc'], dtype='<U32')

In [23]:
c=a[1:3] #array c is a subset of array a

In [24]:
c

array([234, 545])

In [25]:
c[:]=456 # we edit the value of c

In [26]:
c

array([456, 456])

In [27]:
a # it even CHANGES the corresponding values in the original array a!!!!!!

array([ 21, 456, 456, 123])

In [28]:
# Done as a way to save memory, if you need a copy, perform a method on the array
d=a.copy()

In [29]:
a

array([ 21, 456, 456, 123])

In [30]:
d #copy made

array([ 21, 456, 456, 123])

In [31]:
d[0]=1111 #editing a value

In [32]:
d

array([1111,  456,  456,  123])

In [33]:
a # original not affected

array([ 21, 456, 456, 123])