In [1]:
import numpy as np

In [2]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [4]:
r=np.array(revenue)

In [5]:
r

array([14574.49,  7606.46,  8611.41,  9175.41,  8058.65,  8105.44,
       11496.28,  9766.09, 10305.32, 14379.96, 10713.97, 15433.5 ])

In [6]:
e=np.array(expenses)
e

array([12051.82,  5695.07, 12319.2 , 12089.72,  8658.57,   840.2 ,
        3285.73,  5821.12,  6976.93, 16618.61, 10054.37,  3803.96])

In [7]:
p=r-e

In [8]:
p

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [9]:
pat=p*0.7

In [10]:
pat

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [27]:
profitMargin=(pat/r)*100

In [28]:
profitMargin

array([ 12.11616324,  17.58995643, -30.13969838, -22.23352417,
        -5.21109615,  62.74388559,  49.99343266,  28.27619856,
        22.60844884, -10.89749207,   4.30951365,  52.74680403])

In [29]:
m=pat.mean()
m

1750.6813333333332

In [30]:
Good_months=p>m

In [31]:
Good_months

array([ True,  True, False, False, False,  True,  True,  True,  True,
       False, False,  True])

In [32]:
Bad_months=p<m
Bad_months

array([False, False,  True,  True,  True, False, False, False, False,
        True,  True, False])

In [35]:
Best_month_value=max(pat)

In [36]:
Best_month_value

8140.678

In [37]:
Best_month=list()

In [38]:
Best_month = (pat==max(pat))

In [39]:
Best_month

array([False, False, False, False, False, False, False, False, False,
       False, False,  True])

In [41]:
Worst_month=[]
Worst_month=(pat==min(pat))
Worst_month

array([False, False,  True, False, False, False, False, False, False,
       False, False, False])